# NOTICE!!!!!!!
# All times are in EST! (Server's time)

# See: https://github.com/bvandenbos/resque-scheduler
# for examples of this yaml file.

# you can use rufus-scheduler "every" syntax in place of cron if you prefer
# every: 1hr

# cron cheatsheet:
#
# *  *  *  *  *
# -  -  -  -  -
# |  |  |  |  |
# |  |  |  |  +----- day of week (0 - 6) (Sunday=0)
# |  |  |  +------- month (1 - 12)
# |  |  +--------- day of month (1 - 31)
# |  +----------- hour (0 - 23)
# +------------- min (0 - 59)
#
# 0 4 * * *   = Everyday at 4AM
# 0 0 3 4 *   = March 3rd @ Midnight
# 0 10 * * 2  = Every Tuesday at 10AM
# 0 1 * * 1-5 = Mon-Fri at 1AM

# Despite the documentation at https://github.com/resque/resque-scheduler, the queue: value is NOT optional

# 12:00AM
# do_thing:
#   cron: "0 0 * * *"
#   class:
#   queue:
#   args:
#   description: